### ISSUE TITLE
[Initialization] React Native basics

### ISSUE THREAD

**Issue by sapesz-healcloud** [sapesz-healcloud/github-demo#1]
# Goal

To have a working React-Native Hello World App.

# Specification

You need to be able to show a white background with black text saying hello world on both Android simulator and iOS emulator

# Tasks

- [x] Download & install xcode
- [x] Download & install Android studio
- [x] Init React-Native project
- [x] Make code for hello world App

# Risks & Challanges

- Xcode and Android studio install might have some challanges
